export default {
    SET_PRODUCTS: "SET_PRODUCTS",
    SET_SORT_DIRECTION: "SET_SORT_DIRECTION",
    FILTER_PRODUCTS: "FILTER_PRODUCTS",
    FILTER_CITY: "FILTER_CITY",
    PAGINATION_PRODUCTS: "PAGINATION_PRODUCTS",
    SET_LOADING: "SET_LOADING",
    SET_ERROR: "SET_ERROR",
}